apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringboot
spec:
  selector:
    matchLabels:
      app: myspringboot
  template:
    metadata:
      labels:
        app: myspringboot
    spec:
      containers:
      - name: myspringboot
        image: endgaurav/demo-pipeline:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9099
